package com.example.bravobra.domain.state;

public enum OrderState {
    PAYMENT_PENDING, PRODUCT_PREPARING, DELIVERY_PREPARING, DELIVERING, DELIVERED, RETURN_RECEPTION, RETURN_IN_PROGRESS, RETURNED, REFUND_IN_PROGRESS, REFUNDED, ORDER_CANCLED, PURCHASE_CONFIRMED
}
