server:
  port: 80
spring:
  config:
    activate:
      on-profile: yurim

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  h2:
    console:
      enabled: true  # H2 Console`? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  datasource:
    url: jdbc:mysql://localhost:3306/faqs
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace