server:
  port: 80
spring:

  profiles:
    default: devhU
  sql:
    init:
      mode: never
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

  h2:
    console:
      enabled: true  # H2 Console`? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  datasource:
    url: 'jdbc:h2:mem:testdb'
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace